import React, { useState } from 'react';
import { PageHeader } from '../components/layout/PageHeader';
import { Card } from '../components/ui/Card';
import { Select } from '../components/ui/Select';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { useApp } from '../context/AppContext';
import { generateFinancialReportData } from '../math/reportMath';
import { ReportType } from '../types/report';
import { Printer, Download, FileText } from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const { incomes, expenses, bills, budgets, savingsGoals } = useApp();
  const [reportType, setReportType] = useState<ReportType>('INCOME_REPORT');
  const [startDate, setStartDate] = useState('2026-08-01');
  const [endDate, setEndDate] = useState('2026-08-31');

  const reportData = generateFinancialReportData(reportType, startDate, endDate, {
    incomes,
    expenses,
    bills,
    budgets,
    savingsGoals,
  });

  const reportOptions = [
    { label: 'Income & Revenue Audit Report', value: 'INCOME_REPORT' },
    { label: 'Expense Outflow Report', value: 'EXPENSE_REPORT' },
    { label: 'Comprehensive System Audit', value: 'MONTHLY_SUMMARY_REPORT' },
  ];

  const handlePrint = () => {
    window.print();
  };

  const handleExportJSON = () => {
    const jsonStr = JSON.stringify(reportData, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportData.header.title.replace(/\s+/g, '_')}_${Date.now()}.json`;
    a.click();
  };

  return (
    <div className="space-y-6">
      <div className="no-print">
        <PageHeader
          title="Financial Reports & Audits"
          description="Generate customizable audit reports, print summaries, and export financial data."
          action={
            <div className="flex gap-2">
              <Button variant="outline" size="sm" icon={<Printer className="h-4 w-4" />} onClick={handlePrint}>
                Print Preview
              </Button>
              <Button variant="primary" size="sm" icon={<Download className="h-4 w-4" />} onClick={handleExportJSON}>
                Export Report JSON
              </Button>
            </div>
          }
        />

        <Card className="mb-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <Select
              label="Select Report Type"
              value={reportType}
              options={reportOptions}
              onChange={(e) => setReportType(e.target.value as ReportType)}
            />
            <Input label="Start Date" type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} />
            <Input label="End Date" type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} />
          </div>
        </Card>
      </div>

      {/* Printable Report View */}
      <div className="printable-area space-y-6 bg-white dark:bg-slate-900 p-8 rounded-xl border border-slate-200 dark:border-slate-800 shadow-md">
        <div className="flex justify-between items-start border-b border-slate-200 dark:border-slate-800 pb-4">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100">{reportData.header.title}</h2>
            <p className="text-xs text-slate-500">ID: {reportData.header.reportId} • Generated: {reportData.header.generatedAt}</p>
          </div>
          <div className="text-right text-xs text-slate-500">
            <div>Period: {reportData.header.periodStart} to {reportData.header.periodEnd}</div>
            <div>Generated by: {reportData.header.generatedBy}</div>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {Object.entries(reportData.summaryMetrics).map(([key, val]) => (
            <div key={key} className="rounded-lg bg-slate-50 dark:bg-slate-800 p-3 border border-slate-200 dark:border-slate-700">
              <span className="text-[10px] uppercase font-bold text-slate-400 block">{key}</span>
              <span className="text-base font-bold text-slate-900 dark:text-slate-100">{val}</span>
            </div>
          ))}
        </div>

        {/* Table View */}
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border border-slate-200 dark:border-slate-800">
            <thead className="bg-slate-100 dark:bg-slate-800 font-bold uppercase text-slate-600 dark:text-slate-300">
              <tr>
                {reportData.tableColumns.map((col) => (
                  <th key={col} className="p-2 border-b">{col}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
              {reportData.tableRows.map((row, idx) => (
                <tr key={idx}>
                  {reportData.tableColumns.map((col) => (
                    <td key={col} className="p-2 text-slate-700 dark:text-slate-300">{row[col]}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
